theme: jekyll-theme-minimal
title: Gradle GitLab Repositories Plugin
description: Handling Maven GitLab dependencies easy. Define multiple tokens and selectively apply them to repositories.

google_analytics: G-2Z8EZ7QSLC
