/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package at.schrottner.gradle

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

public class GitlabRepositoriesPluginTest extends Specification {
	def "apply to Project"() {
		given:
		def project = ProjectBuilder.builder().build()

		when:
		project.plugins.apply("at.schrottner.gitlab-repositories")

		then:
		project.tasks.findByName("gitLabTask") != null
		project.extensions.findByName(GitlabRepositoriesExtension.NAME) != null
		project.extensions.findByName(GitlabRepositoriesExtension.NAME).tokens.size() > 0
	}
}
