/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package at.schrottner.gradle

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'at.schrottner.gradle.greeting' plugin.
 */
public class GitlabRepositoriesPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("at.schrottner.gradle.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
