/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package at.schrottner.gradle

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

public class GitlabRepositoriesPluginFunctionalTest extends Specification {
    def "can run task"() {
        given:
        def projectDir = new File("build/functionalTest")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle") << """

        """
        new File(projectDir, "build.gradle") << """
            import at.schrottner.gradle.auths.*
            plugins {
                id('at.schrottner.gitlab-repositories')
            }
            gitLab {
                token(PrivateToken) {
                    it.key = 'privateToken'
                    it.value = 'test'
                }
                token(DeployToken) {
                    it.key = 'deployToken'
                    it.value = 'test'
                }
            }
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("gitLabTask", "-i")
        runner.withProjectDir(projectDir)
        runner.withDebug(true)
        def result = runner.build()

        then:
        result.output.contains("GitLab-Repositories added Token: privateToken for Private-Token")
        result.output.contains("GitLab-Repositories added Token: deployToken for Deploy-Token")

    }
}
